from typing import Any

class Response:
    status_code: int
    def raise_for_status(self) -> None: ...
    def json(self) -> Any: ...
    @property
    def text(self) -> str: ...

class AsyncClient:
    def __init__(self, *, timeout: float = ...) -> None: ...
    async def __aenter__(self) -> "AsyncClient": ...
    async def __aexit__(self, *args: Any) -> None: ...
    async def post(self, url: str, *, headers: dict[str, str] | None = ..., json: Any = ...) -> Response: ...
